name: CI pipeline for python
inputs:
  python_version:
    description: 'Python version build'
    required: true
    default: '3.9.7'

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
