name: CI pipeline for python

inputs:
  python_version:
    description: 'Python version build'
    required: true
    default: '3.9.7'

runs:
  using: "composite"
  steps:
    - run: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    - run: Install dependencies
      shell: bash
      command: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
