name: Run CI pipeline to test code

on:
  workflow_call:
    inputs:
      ci-env:
        description: 'build environment'
        type: string
    
jobs:
  run-ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Get env
      run: echo "env is ${{ inputs.ci-env }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - if: ${{ inputs.ci-env == 'python' }}
      name: Run Python CI pipeline
      uses: aggarwalmegha/test-github-actions/.github/actions/python-ci@test-branch
      with:
        python_version: 3.9.7
