name: Run CI pipeline to test code

on:
  workflow_call:
    inputs:
      ci-env:
        description: 'build environment'
        type: string
    
jobs:
  run-ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - if: ${{ inputs.ci-env == 'node' }}
      name: Run Node CI pipeline
      uses: aggarwalmegha/test-github-actions/.github/actions/node-ci@test-branch
      with:
        node_js_version: 18.18.0

    - name: Get env
      run: echo "env is ${{ inputs.ci-env }}"